# Generated by Django 2.2 on 2020-12-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storedetails',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, db_column='Store_name', max_length=1000, null=True)),
                ('store_description', models.CharField(blank=True, db_column='Store_description', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_banner_image')),
            ],
        ),
        migrations.CreateModel(
            name='OpenningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('store', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='App.Storedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='item_name', max_length=1000, null=True)),
                ('price', models.CharField(blank=True, db_column='item_price', max_length=1000, null=True)),
                ('store', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_details', to='App.Storedetails')),
            ],
        ),
    ]
