# Generated by Django 2.2 on 2020-12-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenningTime',
        ),
    ]
