# Generated by Django 2.2 on 2020-12-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_storedetails_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
